name: CI

on:
  push:
    branches:
    - '**'
    - '!dependabot/**'
  pull_request: {}

jobs:

  fats:
    name: test
    runs-on: ubuntu-latest
    env:
      CLUSTER: kind
      REGISTRY: docker-daemon
      DOCKER_BUILDKIT: 1
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Setup env
      run: |
        . ~/.profile
        id="job-$(date +%s)"
        echo "JOB_ID=${id}" >> $GITHUB_ENV
        echo "CLUSTER_NAME=cli-${id}" >> $GITHUB_ENV
        echo "NAMESPACE=cli-${id}" >> $GITHUB_ENV
        nix-env -i -f default.nix
        docker ps
      shell: bash
